Repository Vinnichenko-Ivan/Module6, pull requests merged in 2022-04, with the labels that each got.

#29 Финальные изменения.
  algorithm/cluster.html
  js/cluster/algorithms.js
Labels: fix

#30 Исправления
  ts/pro/decision-tree/audio.js
  ts/pro/decision-tree/audio.ts
  ts/pro/decision-tree/classifier/classifier-id3.js
  ts/pro/decision-tree/classifier/classifier-id3.ts
  ts/pro/decision-tree/main.js
  ts/pro/decision-tree/main.ts
Labels: fix

#33 Feature/genetic algorithm pro
  algorithm/genetic-algorithm-pro.html
  css/genetic-algorithm-pro.css
  js/pro/genetic/genetic-algorithm-pro.js
Labels: feature

#34 Feature/neuron
  algorithm/neuron-pro.html
  algorithm/neuron.html
  js/base/neuron/main.js
  js/base/neuron/utils.js
  js/pro/neuron/main.js
Labels: documentation, refactoring

#36 A*: Добавил звук громче
  ts/pro/a-star/audio.js
  ts/pro/a-star/audio.ts
Labels: fix

#37 Decision Tree: Добавил звук громче
  ts/pro/decision-tree/audio.js
  ts/pro/decision-tree/audio.ts
Labels: fix

#39 Decision Tree: добавил js файлик
  ts/pro/decision-tree/modal.js
Labels: fix

#38 Feature/clasters
  README.md
  algorithm/cluster.html
  js/cluster/clusterAMono.js
  js/pro/cluster/algorithms.js
  js/pro/cluster/clusterAMulti.js
  js/pro/cluster/field.js
  js/pro/cluster/point.js
Labels: documentation, refactoring

#40 Литература.
  js/base/neuron/main.js
Labels: documentation, refactoring

#42 Дерево решений - финал
  algorithm/decision-tree.html
  css/decision-tree.css
  ts/pro/decision-tree/main.js
  ts/pro/decision-tree/main.ts
  ts/pro/decision-tree/modal.js
  ts/pro/decision-tree/modal.ts
Labels: feature

#44 Рефакторинг (библиотеки вынесены в libs)
  algorithm/a-star.html
  algorithm/decision-tree.html
  libs/jquery.js
  libs/require.js
Labels: refactoring

#45 Дерево решений - исправление текста
  algorithm/decision-tree.html
Labels: fix

#49 БАГ ФИКС
  ts/pro/decision-tree/modal.js
  ts/pro/decision-tree/modal.ts
Labels: fix

#43 Удален clusterBeta.html
  algorithm/clusterBeta.html
  css/clusterBeta.css
Labels: refactoring

#50 Фикс громкости
  js/audio.js
Labels: fix
